// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hgfwnbzihgtyeyxfsgws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhnZnduYnppaGd0eWV5eGZzZ3dzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3ODkxOTQsImV4cCI6MjA3NDM2NTE5NH0.Yo2qPp3dgJAh-dMslcgStNWF5q_O8QFFF5Yabdmf4RQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});